realtime-validations-simple/config/routes.rb
RealtimeValidationsSimple::Application.routes.draw do
  resources :products
  resources :sellers

  root :to => "welcome#index"
end

realtime-validations-simple/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :seller

  validates :name, :length => { :minimum => 5 }, :uniqueness => true
  validates :description, :length => { :minimum => 20 }, :allow_blank => true
  validates :seller_id, :presence => { :message => 'Please, select a seller' }
end

realtime-validations-simple/app/models/seller.rb
class Seller < ActiveRecord::Base

  validates :name, :presence => true

end

realtime-validations-simple/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

realtime-validations-simple/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

realtime-validations-simple/app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sellers }
    end
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
    @seller = Seller.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @seller }
    end
  end

  # GET /sellers/new
  # GET /sellers/new.json
  def new
    @seller = Seller.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @seller }
    end
  end

  # GET /sellers/1/edit
  def edit
    @seller = Seller.find(params[:id])
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(params[:seller])

    respond_to do |format|
      if @seller.save
        format.html { redirect_to @seller, notice: 'Seller was successfully created.' }
        format.json { render json: @seller, status: :created, location: @seller }
      else
        format.html { render action: "new" }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sellers/1
  # PUT /sellers/1.json
  def update
    @seller = Seller.find(params[:id])

    respond_to do |format|
      if @seller.update_attributes(params[:seller])
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller = Seller.find(params[:id])
    @seller.destroy

    respond_to do |format|
      format.html { redirect_to sellers_url }
      format.json { head :no_content }
    end
  end
end

realtime-validations-simple/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

realtime-validations-simple/app/helpers/application_helper.rb
module ApplicationHelper
end

realtime-validations-simple/app/helpers/products_helper.rb
module ProductsHelper
end

realtime-validations-simple/app/helpers/sellers_helper.rb
module SellersHelper
end

realtime-validations-simple/app/helpers/welcome_helper.rb
module WelcomeHelper
end

realtime-validations-simple/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RealtimeValidationsSimple</title>
  <%= stylesheet_link_tag    "application", 'realtime_validations/core', :media => "all" %>
  <%= javascript_include_tag "application", 'realtime_validations/core' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

realtime-validations-simple/app/views/products/_form.html.erb
<%= form_validated_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :seller %><br />
    <%= f.select(:seller_id, Seller.all.collect { |s| [ s.name, s.id ] }, { :include_blank => "Select Seller..." }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

realtime-validations-simple/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

realtime-validations-simple/app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Seller</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.seller %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

realtime-validations-simple/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

realtime-validations-simple/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Seller:</b>
  <%= @product.seller %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

realtime-validations-simple/app/views/sellers/_form.html.erb
<%= form_validated_for(@seller) do |f| %>
  <% if @seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

      <ul>
      <% @seller.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birth %><br />
    <%= f.date_select :birth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

realtime-validations-simple/app/views/sellers/edit.html.erb
<h1>Editing seller</h1>

<%= render 'form' %>

<%= link_to 'Show', @seller %> |
<%= link_to 'Back', sellers_path %>

realtime-validations-simple/app/views/sellers/index.html.erb
<h1>Listing sellers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Birth</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sellers.each do |seller| %>
  <tr>
    <td><%= seller.name %></td>
    <td><%= seller.birth %></td>
    <td><%= link_to 'Show', seller %></td>
    <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
    <td><%= link_to 'Destroy', seller, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Seller', new_seller_path %>

realtime-validations-simple/app/views/sellers/new.html.erb
<h1>New seller</h1>

<%= render 'form' %>

<%= link_to 'Back', sellers_path %>

realtime-validations-simple/app/views/sellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @seller.name %>
</p>

<p>
  <b>Birth:</b>
  <%= @seller.birth %>
</p>


<%= link_to 'Edit', edit_seller_path(@seller) %> |
<%= link_to 'Back', sellers_path %>

realtime-validations-simple/app/views/welcome/index.html.erb
<%= link_to 'Sellers', sellers_path %><br/>
<%= link_to 'Products', products_path %>